

public class PantallaInicial extends Pantalla {

    private static InterfazMultas stub;
    
    /**
     * Creates new form PantallaInicial
     * @param stub
     */
    public PantallaInicial(InterfazMultas stub) 
    {
        initComponents();
        super.inicializar(500, 600, "Bienvenido a la aplicación de multas de la DGT");
        PantallaInicial.stub = stub;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        logoDGT = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        rbIdentificacion = new javax.swing.JRadioButton();
        rbConsultarPuntos = new javax.swing.JRadioButton();
        rbConsultarMultas = new javax.swing.JRadioButton();
        bAceptar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        logoDGT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logoDGT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logoDGT.jpg"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("Menú consultas");

        buttonGroup1.add(rbIdentificacion);
        rbIdentificacion.setSelected(true);
        rbIdentificacion.setText("Identificación");

        buttonGroup1.add(rbConsultarPuntos);
        rbConsultarPuntos.setText("Consultar puntos");

        buttonGroup1.add(rbConsultarMultas);
        rbConsultarMultas.setText("Consultar multas");

        bAceptar.setText("Aceptar");
        bAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(logoDGT, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(192, 192, 192)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbIdentificacion)
                            .addComponent(jLabel1)
                            .addComponent(rbConsultarPuntos)
                            .addComponent(rbConsultarMultas)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(207, 207, 207)
                        .addComponent(bAceptar)))
                .addContainerGap(161, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logoDGT, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(jLabel1)
                .addGap(46, 46, 46)
                .addComponent(rbIdentificacion)
                .addGap(36, 36, 36)
                .addComponent(rbConsultarPuntos)
                .addGap(34, 34, 34)
                .addComponent(rbConsultarMultas)
                .addGap(60, 60, 60)
                .addComponent(bAceptar)
                .addContainerGap(147, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAceptarActionPerformed
        
        if(rbIdentificacion.isSelected())
            new PantallaIdentificacion(stub).setVisible(true);
        
        else if(rbConsultarPuntos.isSelected())
            new PantallaConsultarPuntos(stub).setVisible(true);
        
        else
            new PantallaConsultarMultas(stub).setVisible(true);
    }//GEN-LAST:event_bAceptarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaInicial(stub).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAceptar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel logoDGT;
    private javax.swing.JRadioButton rbConsultarMultas;
    private javax.swing.JRadioButton rbConsultarPuntos;
    private javax.swing.JRadioButton rbIdentificacion;
    // End of variables declaration//GEN-END:variables
}
